package network;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.InetAddress;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author neo
 */
public class NetworkGUI extends javax.swing.JFrame {

    private Router r1;
    private Router r2;
    private Router r3;
    private Router r4;
    private Router r5;
    private Router r6;
    private client1 c1;
    private client2 c2;

    /**
     * Creates new form NewJFrame
     */
    public NetworkGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        r1port = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        r1nbh1ip = new javax.swing.JTextField();
        r1nbh2ip = new javax.swing.JTextField();
        r1nbh1port = new javax.swing.JTextField();
        r1nbh2port = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        r1table = new javax.swing.JTable();
        r1start = new javax.swing.JButton();
        r1stop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        r1status = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        r2port = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        r2nbh1ip = new javax.swing.JTextField();
        r2nbh2ip = new javax.swing.JTextField();
        r2nbh1port = new javax.swing.JTextField();
        r2nbh2port = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        r2table = new javax.swing.JTable();
        r2start = new javax.swing.JButton();
        r2stop = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        r2status = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        r2port2 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        r2nbh1ip2 = new javax.swing.JTextField();
        r2nbh2ip2 = new javax.swing.JTextField();
        r2nbh1port2 = new javax.swing.JTextField();
        r2nbh2port2 = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        r2table2 = new javax.swing.JTable();
        r2start2 = new javax.swing.JButton();
        r2stop2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        r2status2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        r2port3 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        r2nbh1ip3 = new javax.swing.JTextField();
        r2nbh2ip3 = new javax.swing.JTextField();
        r2nbh1port3 = new javax.swing.JTextField();
        r2nbh2port3 = new javax.swing.JTextField();
        jScrollPane11 = new javax.swing.JScrollPane();
        r2table3 = new javax.swing.JTable();
        r2start3 = new javax.swing.JButton();
        r2stop3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        r2status3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        r2port4 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        r2nbh1ip4 = new javax.swing.JTextField();
        r2nbh2ip4 = new javax.swing.JTextField();
        r2nbh1port4 = new javax.swing.JTextField();
        r2nbh2port4 = new javax.swing.JTextField();
        jScrollPane12 = new javax.swing.JScrollPane();
        r2table4 = new javax.swing.JTable();
        r2start4 = new javax.swing.JButton();
        r2stop4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        r2status4 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        r2port5 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        r2nbh1ip5 = new javax.swing.JTextField();
        r2nbh2ip5 = new javax.swing.JTextField();
        r2nbh1port5 = new javax.swing.JTextField();
        r2nbh2port5 = new javax.swing.JTextField();
        jScrollPane13 = new javax.swing.JScrollPane();
        r2table5 = new javax.swing.JTable();
        r2start5 = new javax.swing.JButton();
        r2stop5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        r2status5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        clientid = new javax.swing.JLabel();
        c1destid = new javax.swing.JTextField();
        c1rip = new javax.swing.JTextField();
        c1rport = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        c1m = new javax.swing.JTextArea();
        c1t = new javax.swing.JTextField();
        c1send = new javax.swing.JButton();
        connect = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        c1port = new javax.swing.JTextField();
        c1destport = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        clientid1 = new javax.swing.JLabel();
        c1destid1 = new javax.swing.JTextField();
        c1rip1 = new javax.swing.JTextField();
        c1rport1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        c1m1 = new javax.swing.JTextArea();
        c1t1 = new javax.swing.JTextField();
        c1send1 = new javax.swing.JButton();
        connect1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        c1port1 = new javax.swing.JTextField();
        c1destport1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Router 1");

        jLabel6.setText("Port");

        r1port.setColumns(5);
        r1port.setText("4106");

        jLabel7.setText("Neighbor 1");

        jLabel8.setText("Neighbor 2");

        r1nbh1ip.setText("127.0.0.1");

        r1nbh2ip.setText("127.0.1.1");

        r1nbh1port.setText("4110");

        r1nbh2port.setText("4112");

        r1table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(r1table);

        r1start.setText("start");
        r1start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1startActionPerformed(evt);
            }
        });

        r1stop.setText("stop");
        r1stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1stopActionPerformed(evt);
            }
        });

        jLabel1.setText("Status");

        r1status.setToolTipText("Status");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(34, 34, 34)
                        .addComponent(r1start)
                        .addGap(33, 33, 33)
                        .addComponent(r1stop)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(r1status, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(r1port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r1nbh1ip)
                            .addComponent(r1nbh2ip, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r1nbh1port, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(r1nbh2port))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(r1start)
                    .addComponent(r1stop)
                    .addComponent(jLabel1)
                    .addComponent(r1status, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(r1port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(r1nbh1ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r1nbh1port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(r1nbh2ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r1nbh2port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel25.setText("Router 2");

        jLabel26.setText("Port");

        r2port.setColumns(5);
        r2port.setText("4110");

        jLabel27.setText("Neighbor 1");

        jLabel28.setText("Neighbor 2");

        r2nbh1ip.setText("127.0.0.1");

        r2nbh2ip.setText("127.0.1.1");

        r2nbh1port.setText("4106");

        r2nbh2port.setText("4114");

        r2table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(r2table);

        r2start.setText("start");
        r2start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2startActionPerformed(evt);
            }
        });

        r2stop.setText("stop");
        r2stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2stopActionPerformed(evt);
            }
        });

        jLabel2.setText("Status");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(34, 34, 34)
                        .addComponent(r2start)
                        .addGap(33, 33, 33)
                        .addComponent(r2stop)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(r2status, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(r2port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r2nbh1ip)
                            .addComponent(r2nbh2ip))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r2nbh1port)
                            .addComponent(r2nbh2port))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(r2start)
                    .addComponent(r2stop)
                    .addComponent(jLabel2)
                    .addComponent(r2status, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(r2port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(r2nbh1ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r2nbh1port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(r2nbh2ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2nbh2port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel33.setText("Router 6");

        jLabel34.setText("Port");

        r2port2.setColumns(5);
        r2port2.setText("4117");

        jLabel35.setText("Neighbor 1");

        jLabel36.setText("Neighbor 2");

        r2nbh1ip2.setText("127.0.0.1");

        r2nbh2ip2.setText("127.0.1.1");

        r2nbh1port2.setText("4116");

        r2nbh2port2.setText("4201");

        r2table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(r2table2);

        r2start2.setText("start");
        r2start2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2start2ActionPerformed(evt);
            }
        });

        r2stop2.setText("stop");
        r2stop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2stop2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Status");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(34, 34, 34)
                        .addComponent(r2start2)
                        .addGap(33, 33, 33)
                        .addComponent(r2stop2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(r2status2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(18, 18, 18)
                        .addComponent(r2port2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r2nbh1ip2)
                            .addComponent(r2nbh2ip2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r2nbh1port2)
                            .addComponent(r2nbh2port2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(r2start2)
                    .addComponent(r2stop2)
                    .addComponent(jLabel4)
                    .addComponent(r2status2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(r2port2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(r2nbh1ip2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r2nbh1port2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(r2nbh2ip2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2nbh2port2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel37.setText("Router 5");

        jLabel38.setText("Port");

        r2port3.setColumns(5);
        r2port3.setText("4116");

        jLabel39.setText("Neighbor 1");

        jLabel40.setText("Neighbor 2");

        r2nbh1ip3.setText("127.0.0.1");

        r2nbh2ip3.setText("127.0.1.1");

        r2nbh1port3.setText("4112");

        r2nbh2port3.setText("4117");

        r2table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane11.setViewportView(r2table3);

        r2start3.setText("start");
        r2start3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2start3ActionPerformed(evt);
            }
        });

        r2stop3.setText("stop");
        r2stop3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2stop3ActionPerformed(evt);
            }
        });

        jLabel9.setText("Status");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(34, 34, 34)
                        .addComponent(r2start3)
                        .addGap(33, 33, 33)
                        .addComponent(r2stop3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(26, 26, 26)
                        .addComponent(r2status3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(18, 18, 18)
                        .addComponent(r2port3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r2nbh2ip3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(r2nbh1ip3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r2nbh1port3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(r2nbh2port3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(r2start3)
                    .addComponent(r2stop3)
                    .addComponent(jLabel9)
                    .addComponent(r2status3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(r2port3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(r2nbh1ip3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r2nbh1port3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(r2nbh2ip3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2nbh2port3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel41.setText("Router 4");

        jLabel42.setText("Port");

        r2port4.setColumns(5);
        r2port4.setText("4114");

        jLabel43.setText("Neighbor 1");

        jLabel44.setText("Neighbor 2");

        r2nbh1ip4.setText("127.0.0.1");

        r2nbh2ip4.setText("127.0.1.1");

        r2nbh1port4.setText("4110");

        r2nbh2port4.setText("4200");

        r2table4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane12.setViewportView(r2table4);

        r2start4.setText("start");
        r2start4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2start4ActionPerformed(evt);
            }
        });

        r2stop4.setText("stop");
        r2stop4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2stop4ActionPerformed(evt);
            }
        });

        jLabel10.setText("Status");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addGap(34, 34, 34)
                        .addComponent(r2start4)
                        .addGap(33, 33, 33)
                        .addComponent(r2stop4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(26, 26, 26)
                        .addComponent(r2status4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addGap(18, 18, 18)
                        .addComponent(r2port4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r2nbh1ip4)
                            .addComponent(r2nbh2ip4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r2nbh1port4)
                            .addComponent(r2nbh2port4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(r2start4)
                    .addComponent(r2stop4)
                    .addComponent(jLabel10)
                    .addComponent(r2status4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(r2port4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel43)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(r2nbh1ip4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r2nbh1port4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(r2nbh2ip4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2nbh2port4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel45.setText("Router 3");

        jLabel46.setText("Port");

        r2port5.setColumns(5);
        r2port5.setText("4112");

        jLabel47.setText("Neighbor 1");

        jLabel48.setText("Neighbor 2");

        r2nbh1ip5.setText("127.0.0.1");

        r2nbh2ip5.setText("127.0.1.1");

        r2nbh1port5.setText("4106");

        r2nbh2port5.setText("4116");

        r2table5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane13.setViewportView(r2table5);

        r2start5.setText("start");
        r2start5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2start5ActionPerformed(evt);
            }
        });

        r2stop5.setText("stop");
        r2stop5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2stop5ActionPerformed(evt);
            }
        });

        jLabel11.setText("Status");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addGap(34, 34, 34)
                        .addComponent(r2start5)
                        .addGap(33, 33, 33)
                        .addComponent(r2stop5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(26, 26, 26)
                        .addComponent(r2status5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addGap(18, 18, 18)
                        .addComponent(r2port5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r2nbh1ip5)
                            .addComponent(r2nbh2ip5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r2nbh1port5)
                            .addComponent(r2nbh2port5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(r2start5)
                    .addComponent(r2stop5)
                    .addComponent(jLabel11)
                    .addComponent(r2status5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(r2port5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel47)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(r2nbh1ip5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r2nbh1port5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(r2nbh2ip5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2nbh2port5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Client 1");

        jLabel12.setText("your id");

        jLabel13.setText("dest id");

        c1rip.setText("127.0.0.1");

        c1rport.setText("04106");

        jLabel14.setText("<html>Gateway/Route Ip <br>and port</html>");
        jLabel14.setName(""); // NOI18N

        c1m.setColumns(20);
        c1m.setRows(5);
        jScrollPane2.setViewportView(c1m);

        c1send.setText("send");
        c1send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1sendActionPerformed(evt);
            }
        });

        connect.setText("Connect To Router");
        connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectActionPerformed(evt);
            }
        });

        jLabel15.setText("Port");

        c1port.setText("51200");

        c1destport.setText("51201");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(c1t, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(c1send))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(c1destid, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(c1destport, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(clientid, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(connect)
                .addGap(28, 28, 28))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(34, 34, 34)
                                .addComponent(c1port))
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c1rip, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(c1rport, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(c1port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1rip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1rport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(clientid))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c1destid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(c1destport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c1t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1send))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setText("Client 2");

        jLabel17.setText("your id");

        jLabel18.setText("dest id");

        c1rip1.setText("127.0.0.1");

        c1rport1.setText("04117");

        jLabel19.setText("<html>Gateway/Route Ip <br>and port</html>");
        jLabel19.setName(""); // NOI18N

        c1m1.setColumns(20);
        c1m1.setRows(5);
        jScrollPane4.setViewportView(c1m1);

        c1send1.setText("send");
        c1send1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1send1ActionPerformed(evt);
            }
        });

        connect1.setText("Connect To Router");
        connect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connect1ActionPerformed(evt);
            }
        });

        jLabel20.setText("Port");

        c1port1.setText("51201");

        c1destport1.setText("51200");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(c1t1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(c1send1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(c1destid1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(c1destport1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(clientid1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(connect1)
                .addGap(28, 28, 28))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(34, 34, 34)
                                .addComponent(c1port1))
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c1rip1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(c1rport1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel16)
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(c1port1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1rip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1rport1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connect1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(clientid1))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c1destid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(c1destport1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c1t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1send1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(1970, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1007, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r2start5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2start5ActionPerformed
        try {
            int port = Integer.parseInt(r2port5.getText());
            r3 = new Router(port);
            r2status5.setText("Running");
            r3.getRoutingTable().add(r3.nextId.incrementAndGet(), "127.0.1.1", 0);
            r3.getRoutingTable().add(r3.nextId.incrementAndGet(), "127.0.0.1", 0);
            r3.addNeighborRouter(InetAddress.getByName(r2nbh1ip5.getText()), Integer.parseInt(r2nbh1port5.getText()));
            r3.addNeighborRouter(InetAddress.getByName(r2nbh2ip5.getText()), Integer.parseInt(r2nbh2port5.getText()));
            (new Thread(new r3TableUpdate())).start();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(NetworkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_r2start5ActionPerformed

    private void r2start4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2start4ActionPerformed
        try {
            int port = Integer.parseInt(r2port4.getText());
            r4 = new Router(port);
            r2status4.setText("Running");
            r4.getRoutingTable().add(r4.nextId.incrementAndGet(), "127.0.1.1", 0);
            r4.getRoutingTable().add(r4.nextId.incrementAndGet(), "127.0.0.1", 0);
            r4.addNeighborRouter(InetAddress.getByName(r2nbh1ip4.getText()), Integer.parseInt(r2nbh1port4.getText()));
            r4.addNeighborRouter(InetAddress.getByName(r2nbh2ip4.getText()), Integer.parseInt(r2nbh2port4.getText()));
            (new Thread(new r4TableUpdate())).start();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(NetworkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_r2start4ActionPerformed

    private void r2start3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2start3ActionPerformed
        try {
            int port = Integer.parseInt(r2port3.getText());
            r5 = new Router(port);
            r2status3.setText("Running");
            r5.getRoutingTable().add(r5.nextId.incrementAndGet(), "127.0.0.1", 0);
            r5.getRoutingTable().add(r5.nextId.incrementAndGet(), "127.0.1.1", 0);
            r5.addNeighborRouter(InetAddress.getByName(r2nbh1ip3.getText()), Integer.parseInt(r2nbh1port3.getText()));
            r5.addNeighborRouter(InetAddress.getByName(r2nbh2ip3.getText()), Integer.parseInt(r2nbh2port3.getText()));
            (new Thread(new r5TableUpdate())).start();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(NetworkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_r2start3ActionPerformed

    private void r2start2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2start2ActionPerformed
        try {
            int port = Integer.parseInt(r2port2.getText());
            r6 = new Router(port);
            r2status2.setText("Running");
            r6.getRoutingTable().add(r6.nextId.incrementAndGet(), "127.0.0.1", 0);
            r6.getRoutingTable().add(r6.nextId.incrementAndGet(), "127.0.1.1", 0);
            r6.addNeighborRouter(InetAddress.getByName(r2nbh1ip2.getText()), Integer.parseInt(r2nbh1port2.getText()));
            r6.addNeighborRouter(InetAddress.getByName(r2nbh2ip2.getText()), Integer.parseInt(r2nbh2port2.getText()));
            (new Thread(new r6TableUpdate())).start();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(NetworkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_r2start2ActionPerformed

    private void r2startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2startActionPerformed
        try {
            int port = Integer.parseInt(r2port.getText());
            r2 = new Router(port);
            r2status.setText("Running");
            r2.getRoutingTable().add(r2.nextId.incrementAndGet(), "127.0.0.1", 0);
            r2.getRoutingTable().add(r2.nextId.incrementAndGet(), "127.0.1.1", 0);
            r2.addNeighborRouter(InetAddress.getByName(r2nbh1ip.getText()), Integer.parseInt(r2nbh1port.getText()));
            r2.addNeighborRouter(InetAddress.getByName(r2nbh2ip.getText()), Integer.parseInt(r2nbh2port.getText()));
            (new Thread(new r2TableUpdate())).start();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(NetworkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_r2startActionPerformed

    private void r1startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1startActionPerformed
        // TODO add your handling code here:
        try {
            int port = Integer.parseInt(r1port.getText());
            r1 = new Router(port);
            r1status.setText("Running");
            r1.getRoutingTable().add(r1.nextId.incrementAndGet(), "127.0.0.1", 0);
            r1.getRoutingTable().add(r1.nextId.incrementAndGet(), "127.0.1.1", 0);
            r1.addNeighborRouter(InetAddress.getByName(r1nbh1ip.getText()), Integer.parseInt(r1nbh1port.getText()));
            r1.addNeighborRouter(InetAddress.getByName(r1nbh2ip.getText()), Integer.parseInt(r1nbh2port.getText()));
            (new Thread(new r1TableUpdate())).start();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(NetworkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_r1startActionPerformed

    private void connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectActionPerformed
        try {
            String client1rip = this.c1rip.getText();
            String client1rport = this.c1rport.getText();
            String client1port = this.c1port.getText();
            c1 = new client1(client1rip, client1rport, client1port);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(NetworkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_connectActionPerformed

    private void connect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connect1ActionPerformed
        try {
            String client1rip = this.c1rip1.getText();
            String client1rport = this.c1rport1.getText();
            String client1port = this.c1port1.getText();
            c2 = new client2(client1rip, client1rport, client1port);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(NetworkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_connect1ActionPerformed

    private void c1sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1sendActionPerformed
        try {
            c1.sendMessage(c1t.getText(), c1destid.getText(), c1destport.getText());
            c1t.setText("");
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(NetworkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_c1sendActionPerformed

    private void c1send1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1send1ActionPerformed
        try {
            c2.sendMessage(c1t1.getText(), c1destid1.getText(), c1destport1.getText());
            c1t1.setText("");
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(NetworkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_c1send1ActionPerformed

    private void r2stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2stopActionPerformed
        // TODO add your handling code here:
        r2.setIsRunning(false);
        r2 = null;
        r2status.setText("Stoped");

    }//GEN-LAST:event_r2stopActionPerformed

    private void r1stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1stopActionPerformed
        // TODO add your handling code here:
        r1.setIsRunning(false);
        r1 = null;
        r1status.setText("Stoped");
    }//GEN-LAST:event_r1stopActionPerformed

    private void r2stop5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2stop5ActionPerformed
        // TODO add your handling code here:
        r3.setIsRunning(false);
        r3 = null;
        r2status5.setText("Stoped");
    }//GEN-LAST:event_r2stop5ActionPerformed

    private void r2stop4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2stop4ActionPerformed
        // TODO add your handling code here:
        r4.setIsRunning(false);
        r4 = null;
        r2status4.setText("Stoped");
    }//GEN-LAST:event_r2stop4ActionPerformed

    private void r2stop3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2stop3ActionPerformed
        // TODO add your handling code here:
        r5.setIsRunning(false);
        r5 = null;
        r2status3.setText("Stoped");
    }//GEN-LAST:event_r2stop3ActionPerformed

    private void r2stop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2stop2ActionPerformed
        // TODO add your handling code here:
        r6.setIsRunning(false);
        r6 = null;
        r2status2.setText("Stoped");
    }//GEN-LAST:event_r2stop2ActionPerformed

    class client1 extends Network {

        public client1(String routerIp, String routerPort, String port) {
            super(routerIp, routerPort, port);
            (new Thread(new receivePacket())).start();
        }

        class receivePacket implements Runnable {

            public void run() {
                while (true) {
                    try {
                        handlePacket();
                    } catch (IOException e) {
                        System.err.println(e.getMessage());
                        continue;
                    }
                }
            }

        }

        public void sendMessage(String message, String destId, String destPort) {

            byte[] data = BuildPacket(message, destId, destPort);
            try {
                InetAddress router = InetAddress.getByName(routerIp);
                System.out.println(new String(data, "UTF-8").trim());
                DatagramPacket theOutput
                        = new DatagramPacket(data, data.length, router, Integer.parseInt(routerPort));
                socket.send(theOutput);
                c1m.append("\n You:" + message);
                System.out.println("Sent Message");
            } catch (Exception ex) {
                System.out.println("network.Client.sendMessage()" + ex.getMessage());
            }
        }

        public String getSrcId() {
            return this.srcId;
        }

        private void handlePacket() throws IOException {
            DatagramPacket recvPacket = receivePacket();
            byte[] data = recvPacket.getData();
            //System.out.println("network.Client.handlePacket() got packet form Router");
            //String reponseString = new String(data, "UTF-8").trim();
            //System.out.println("network.Client.handlePacket()" + reponseString);

            //Checking router packet
            if ((char) (data[0] & 0xFF) == 'R' && (char) (data[1] & 0xFF) == 'e' && (char) (data[2] & 0xFF) == 'g') {
                regRespnseFromRouter(recvPacket);
                clientid.setText(srcId);
                return;
            }

            String dataInString = receiveMessage(recvPacket);
            c1m.append("\n Friend : " + dataInString.trim());
            System.out.println("c1 Message " + dataInString);

        }

        private DatagramPacket receivePacket() throws IOException {
            byte[] buffer = new byte[65535];

            DatagramPacket recvPacket = new DatagramPacket(buffer, buffer.length);
            socket.receive(recvPacket);

            return recvPacket;
        }

    }

    class client2 extends Network {

        public client2(String routerIp, String routerPort, String port) {
            super(routerIp, routerPort, port);
            (new Thread(new receivePacket())).start();
        }

        class receivePacket implements Runnable {

            public void run() {
                while (true) {
                    try {
                        handlePacket();
                    } catch (IOException e) {
                        System.err.println(e.getMessage());
                        continue;
                    }
                }
            }

        }

        public void sendMessage(String message, String destId, String destPort) {

            byte[] data = BuildPacket(message, destId, destPort);
            try {
                InetAddress router = InetAddress.getByName(routerIp);
                System.out.println(new String(data, "UTF-8").trim());
                DatagramPacket theOutput
                        = new DatagramPacket(data, data.length, router, Integer.parseInt(routerPort));
                socket.send(theOutput);
                c1m1.append("\n You:" + message);
                System.out.println("Sent Message");
            } catch (Exception ex) {
                System.out.println("network.Client.sendMessage()" + ex.getMessage());
            }
        }

        public String getSrcId() {
            return this.srcId;
        }

        private void handlePacket() throws IOException {
            DatagramPacket recvPacket = receivePacket();
            byte[] data = recvPacket.getData();
            //System.out.println("network.Client.handlePacket() got packet form Router");
            //String reponseString = new String(data, "UTF-8").trim();
            //System.out.println("network.Client.handlePacket()" + reponseString);

            //Checking router packet
            if ((char) (data[0] & 0xFF) == 'R' && (char) (data[1] & 0xFF) == 'e' && (char) (data[2] & 0xFF) == 'g') {
                regRespnseFromRouter(recvPacket);
                clientid1.setText(srcId);
                return;
            }

            String dataInString = receiveMessage(recvPacket);
            c1m1.append("\n Friend : " + dataInString.trim());
            System.out.println("c2 Message " + dataInString);

        }

        private DatagramPacket receivePacket() throws IOException {
            byte[] buffer = new byte[65535];

            DatagramPacket recvPacket = new DatagramPacket(buffer, buffer.length);
            socket.receive(recvPacket);

            return recvPacket;
        }

    }

    class r1TableUpdate implements Runnable {

        boolean isRunning = true;

        public void run() {
            while (isRunning) {
                DefaultTableModel model = new DefaultTableModel();
                model.setColumnCount(4);
                Vector<String> cols = new Vector();
                cols.add("ID");
                cols.add("IP address");
                cols.add("Cost/Hop");
                cols.add("port");
                model.setColumnIdentifiers(cols);
                if (r1 == null) {
                    isRunning = false;
                    continue;
                }
                RouterTable routingTable = r1.getRoutingTable();

                for (Integer name : routingTable.getTable().keySet()) {
                    Vector<String> rows = new Vector();
                    String key = name.toString();
                    List<String> value = routingTable.getTable().get(name);
                    rows.add(key);
                    rows.add(value.get(0));
                    rows.add(value.get(1));
                    rows.add(value.get(2));
                    model.addRow(rows);
                }
                r1table.setModel(model);
                try {
                    Thread.sleep(5000);
                } catch (InterruptedException ex) {
                    System.out.println("network.NewJFrame.r1TableUpdate.run()");
                    java.util.logging.Logger.getLogger(NetworkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        }
    }

    class r2TableUpdate implements Runnable {

        boolean isRunning = true;

        public void run() {
            while (isRunning) {
                DefaultTableModel model = new DefaultTableModel();
                model.setColumnCount(4);
                Vector<String> cols = new Vector();
                cols.add("ID");
                cols.add("IP address");
                cols.add("Cost/Hop");
                cols.add("port");
                model.setColumnIdentifiers(cols);
                if (r2 == null) {
                    isRunning = false;
                    continue;
                }
                RouterTable routingTable = r2.getRoutingTable();

                for (Integer name : routingTable.getTable().keySet()) {
                    Vector<String> rows = new Vector();
                    String key = name.toString();
                    List<String> value = routingTable.getTable().get(name);
                    rows.add(key);
                    rows.add(value.get(0));
                    rows.add(value.get(1));
                    rows.add(value.get(2));
                    model.addRow(rows);
                }
                r2table.setModel(model);
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    System.out.println("network.NewJFrame.r2TableUpdate.run()");
                    java.util.logging.Logger.getLogger(NetworkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        }
    }

    class r3TableUpdate implements Runnable {

        boolean isRunning = true;

        public void run() {
            while (isRunning) {
                DefaultTableModel model = new DefaultTableModel();
                model.setColumnCount(4);
                Vector<String> cols = new Vector();
                cols.add("ID");
                cols.add("IP address");
                cols.add("Cost/Hop");
                cols.add("port");
                model.setColumnIdentifiers(cols);
                if (r3 == null) {
                    isRunning = false;
                    continue;
                }
                RouterTable routingTable = r3.getRoutingTable();

                for (Integer name : routingTable.getTable().keySet()) {
                    Vector<String> rows = new Vector();
                    String key = name.toString();
                    List<String> value = routingTable.getTable().get(name);
                    rows.add(key);
                    rows.add(value.get(0));
                    rows.add(value.get(1));
                    rows.add(value.get(2));
                    model.addRow(rows);
                }
                r2table5.setModel(model);
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    System.out.println("network.NewJFrame.r2TableUpdate.run()");
                    java.util.logging.Logger.getLogger(NetworkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        }
    }

    class r4TableUpdate implements Runnable {

        boolean isRunning = true;

        public void run() {
            while (isRunning) {
                DefaultTableModel model = new DefaultTableModel();
                model.setColumnCount(4);
                Vector<String> cols = new Vector();
                cols.add("ID");
                cols.add("IP address");
                cols.add("Cost/Hop");
                cols.add("port");
                model.setColumnIdentifiers(cols);
                if (r4 == null) {
                    isRunning = false;
                    continue;
                }
                RouterTable routingTable = r4.getRoutingTable();

                for (Integer name : routingTable.getTable().keySet()) {
                    Vector<String> rows = new Vector();
                    String key = name.toString();
                    List<String> value = routingTable.getTable().get(name);
                    rows.add(key);
                    rows.add(value.get(0));
                    rows.add(value.get(1));
                    rows.add(value.get(2));
                    model.addRow(rows);
                }
                r2table4.setModel(model);
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    System.out.println("network.NewJFrame.r2TableUpdate.run()");
                    java.util.logging.Logger.getLogger(NetworkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        }
    }

    class r5TableUpdate implements Runnable {

        boolean isRunning = true;

        public void run() {
            while (isRunning) {
                DefaultTableModel model = new DefaultTableModel();
                model.setColumnCount(4);
                Vector<String> cols = new Vector();
                cols.add("ID");
                cols.add("IP address");
                cols.add("Cost/Hop");
                cols.add("port");
                model.setColumnIdentifiers(cols);
                if (r5 == null) {
                    isRunning = false;
                    continue;
                }
                RouterTable routingTable = r5.getRoutingTable();

                for (Integer name : routingTable.getTable().keySet()) {
                    Vector<String> rows = new Vector();
                    String key = name.toString();
                    List<String> value = routingTable.getTable().get(name);
                    rows.add(key);
                    rows.add(value.get(0));
                    rows.add(value.get(1));
                    rows.add(value.get(2));
                    model.addRow(rows);
                }
                r2table3.setModel(model);
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    System.out.println("network.NewJFrame.r2TableUpdate.run()");
                    java.util.logging.Logger.getLogger(NetworkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        }
    }

    class r6TableUpdate implements Runnable {

        boolean isRunning = true;

        public void run() {
            while (isRunning) {
                DefaultTableModel model = new DefaultTableModel();
                model.setColumnCount(4);
                Vector<String> cols = new Vector();
                cols.add("ID");
                cols.add("IP address");
                cols.add("Cost/Hop");
                cols.add("port");
                model.setColumnIdentifiers(cols);
                if (r6 == null) {
                    isRunning = false;
                    continue;
                }
                RouterTable routingTable = r6.getRoutingTable();

                for (Integer name : routingTable.getTable().keySet()) {
                    Vector<String> rows = new Vector();
                    String key = name.toString();
                    List<String> value = routingTable.getTable().get(name);
                    rows.add(key);
                    rows.add(value.get(0));
                    rows.add(value.get(1));
                    rows.add(value.get(2));
                    model.addRow(rows);
                }
                r2table2.setModel(model);
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    System.out.println("network.NewJFrame.r2TableUpdate.run()");
                    java.util.logging.Logger.getLogger(NetworkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NetworkGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NetworkGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NetworkGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NetworkGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NetworkGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c1destid;
    private javax.swing.JTextField c1destid1;
    private javax.swing.JTextField c1destport;
    private javax.swing.JTextField c1destport1;
    private javax.swing.JTextArea c1m;
    private javax.swing.JTextArea c1m1;
    private javax.swing.JTextField c1port;
    private javax.swing.JTextField c1port1;
    private javax.swing.JTextField c1rip;
    private javax.swing.JTextField c1rip1;
    private javax.swing.JTextField c1rport;
    private javax.swing.JTextField c1rport1;
    private javax.swing.JButton c1send;
    private javax.swing.JButton c1send1;
    private javax.swing.JTextField c1t;
    private javax.swing.JTextField c1t1;
    private javax.swing.JLabel clientid;
    private javax.swing.JLabel clientid1;
    private javax.swing.JButton connect;
    private javax.swing.JButton connect1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField r1nbh1ip;
    private javax.swing.JTextField r1nbh1port;
    private javax.swing.JTextField r1nbh2ip;
    private javax.swing.JTextField r1nbh2port;
    private javax.swing.JTextField r1port;
    private javax.swing.JButton r1start;
    private javax.swing.JLabel r1status;
    private javax.swing.JButton r1stop;
    private javax.swing.JTable r1table;
    private javax.swing.JTextField r2nbh1ip;
    private javax.swing.JTextField r2nbh1ip2;
    private javax.swing.JTextField r2nbh1ip3;
    private javax.swing.JTextField r2nbh1ip4;
    private javax.swing.JTextField r2nbh1ip5;
    private javax.swing.JTextField r2nbh1port;
    private javax.swing.JTextField r2nbh1port2;
    private javax.swing.JTextField r2nbh1port3;
    private javax.swing.JTextField r2nbh1port4;
    private javax.swing.JTextField r2nbh1port5;
    private javax.swing.JTextField r2nbh2ip;
    private javax.swing.JTextField r2nbh2ip2;
    private javax.swing.JTextField r2nbh2ip3;
    private javax.swing.JTextField r2nbh2ip4;
    private javax.swing.JTextField r2nbh2ip5;
    private javax.swing.JTextField r2nbh2port;
    private javax.swing.JTextField r2nbh2port2;
    private javax.swing.JTextField r2nbh2port3;
    private javax.swing.JTextField r2nbh2port4;
    private javax.swing.JTextField r2nbh2port5;
    private javax.swing.JTextField r2port;
    private javax.swing.JTextField r2port2;
    private javax.swing.JTextField r2port3;
    private javax.swing.JTextField r2port4;
    private javax.swing.JTextField r2port5;
    private javax.swing.JButton r2start;
    private javax.swing.JButton r2start2;
    private javax.swing.JButton r2start3;
    private javax.swing.JButton r2start4;
    private javax.swing.JButton r2start5;
    private javax.swing.JLabel r2status;
    private javax.swing.JLabel r2status2;
    private javax.swing.JLabel r2status3;
    private javax.swing.JLabel r2status4;
    private javax.swing.JLabel r2status5;
    private javax.swing.JButton r2stop;
    private javax.swing.JButton r2stop2;
    private javax.swing.JButton r2stop3;
    private javax.swing.JButton r2stop4;
    private javax.swing.JButton r2stop5;
    private javax.swing.JTable r2table;
    private javax.swing.JTable r2table2;
    private javax.swing.JTable r2table3;
    private javax.swing.JTable r2table4;
    private javax.swing.JTable r2table5;
    // End of variables declaration//GEN-END:variables
}
